# Generated by Django 3.1.2 on 2020-12-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_notification_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_code',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
