# Generated by Django 3.1.2 on 2020-12-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201202_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_with',
            field=models.CharField(default='', max_length=1, null=True),
        ),
    ]
