# Generated by Django 3.1.2 on 2020-12-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser_verified_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_code',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
