# Generated by Django 3.1.2 on 2020-12-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customuser_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='back',
            field=models.ImageField(default='', null=True, upload_to='back'),
        ),
    ]
