# Generated by Django 3.1 on 2021-07-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_customuser_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthDay',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthMonth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthYear',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
